# Generated by Django 5.0.7 on 2024-09-25 10:06

from django.db import migrations
import os


def create_admin_user(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    name = os.environ.get('DJANGO_ADMIN_USERNAME', 'admin')
    password = os.environ.get('DJANGO_ADMIN_PASSWORD', 'adminpassword')  # Use a secure password
    email = os.environ.get('DJANGO_ADMIN_EMAIL', 'admin@example.com')
    
    if not User.objects.filter(email=email).exists():
        User.objects.create_superuser(name=name, password=password, email=email)

def delete_admin_user(apps, schema_editor):
    # Get the User model from the apps registry to avoid issues with model imports
    User = apps.get_model('accounts', 'User')
    
    # Delete the created admin user
    User.objects.filter(name='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_paid'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, delete_admin_user),
    ]
